# Generated by Django 2.1.2 on 2019-01-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardMallServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carduser',
            name='code_id',
            field=models.CharField(default='no_codeid', max_length=150, verbose_name='代码标识'),
        ),
        migrations.AddField(
            model_name='carduser',
            name='code_url',
            field=models.CharField(default='no_codeurl', max_length=512, verbose_name='代码地址'),
        ),
        migrations.AddField(
            model_name='carduser',
            name='created_at',
            field=models.CharField(default='no_createtime', max_length=150, verbose_name='账户创建时间'),
        ),
        migrations.AddField(
            model_name='carduser',
            name='identity_number',
            field=models.CharField(default='no_identitynumber', max_length=150, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='carduser',
            name='session_id',
            field=models.CharField(default='no_sessionid', max_length=150, verbose_name='session'),
        ),
    ]
